version: '{build}'
os: Visual Studio 2015
configuration: Release
platform: Any CPU
skip_tags: true
before_build:
  - ps: nuget restore
build:
  project: Scallion.Tools.sln
  verbosity: minimal
  publish_nuget: true
artifacts:
  - path: Scallion.Tools.Essentials\bin\$(configuration)
    name: Scallion.Tools.Essentials
deploy:
  - provider: GitHub
    tag: build-$(appveyor_build_version)
    release: MikuMikuUtils Build $(appveyor_build_version)
    auth_token:
      secure: KkbkUfg5iFaqdqxRAHRvPZv5+nfF99DyufxN6IijxL2TWoV3QTdkAkrnyNvIPt9+
    artifact: Scallion.Tools.Essentials
    draft: true
    on:
      branch: master
  - provider: NuGet
    api_key:
      secure: fb6UDblafl4cIHQVhvG2PO5erdbxkG7Rv18HagRKkrbcLS6+fmu3OQi1LsD7uZF5
    on:
      branch: master
cache:
  - packages -> **\packages.config
